#!/bin/sh -e
# slippi-appimage-installer
# Simple wrapper script around Dolphin; initializes configuration files in
# XDG_CONFIG_HOME. This should only run once, if at all (just to bootstrap
# your installation).

CFGDIR="${HOME}/.config/SlippiDolphin"
if [ ! -e ${CFGDIR} ]; then
	mkdir -p ${CFGDIR}
	cp -R ./Overwrite/Sys/* ${CFGDIR}/Sys/
	cp -R ./Overwrite/User/* ${CFGDIR}/User/
else
	echo "[*] Sysdir already configured"
fi
