// Copyright 2008 Dolphin Emulator Project
// Licensed under GPLv2+
// Refer to the license.txt file included.

#include <cstring>
#include <string>

#include "Common/CommonFuncs.h"
#include "Common/CommonTypes.h"
#include "Common/MsgHandler.h"

#include "Core/Boot/ElfReader.h"
#include "Core/Debugger/Debugger_SymbolMap.h"
#include "Core/HW/Memmap.h"
#include "Core/PowerPC/PPCSymbolDB.h"

static void bswap(u32& w)
{
	w = Common::swap32(w);
}
static void bswap(u16& w)
{
	w = Common::swap16(w);
}

static void byteswapHeader(Elf32_Ehdr& ELF_H)
{
	bswap(ELF_H.e_type);
	bswap(ELF_H.e_machine);
	bswap(ELF_H.e_ehsize);
	bswap(ELF_H.e_phentsize);
	bswap(ELF_H.e_phnum);
	bswap(ELF_H.e_shentsize);
	bswap(ELF_H.e_shnum);
	bswap(ELF_H.e_shstrndx);
	bswap(ELF_H.e_version);
	bswap(ELF_H.e_entry);
	bswap(ELF_H.e_phoff);
	bswap(ELF_H.e_shoff);
	bswap(ELF_H.e_flags);
}

static void byteswapSegment(Elf32_Phdr& sec)
{
	bswap(sec.p_align);
	bswap(sec.p_filesz);
	bswap(sec.p_flags);
	bswap(sec.p_memsz);
	bswap(sec.p_offset);
	bswap(sec.p_paddr);
	bswap(sec.p_vaddr);
	bswap(sec.p_type);
}

static void byteswapSection(Elf32_Shdr& sec)
{
	bswap(sec.sh_addr);
	bswap(sec.sh_addralign);
	bswap(sec.sh_entsize);
	bswap(sec.sh_flags);
	bswap(sec.sh_info);
	bswap(sec.sh_link);
	bswap(sec.sh_name);
	bswap(sec.sh_offset);
	bswap(sec.sh_size);
	bswap(sec.sh_type);
}

ElfReader::ElfReader(void* ptr, size_t size)
{
	base = (char*)ptr;
	base32 = (u32*)ptr;
	m_size = size;
	m_is_valid = Initialize();
}

bool ElfReader::Initialize()
{
	if (!base || m_size < sizeof(Elf32_Ehdr))
	{
		ERROR_LOG(BOOT, "ELF file is too small.");
		return false;
	}

	header = (Elf32_Ehdr*)base;
	if (header->e_ident[EI_MAG0] != ELFMAG0 || header->e_ident[EI_MAG1] != ELFMAG1 ||
		header->e_ident[EI_MAG2] != ELFMAG2 || header->e_ident[EI_MAG3] != ELFMAG3 ||
		header->e_ident[EI_CLASS] != ELFCLASS32 || header->e_ident[EI_DATA] != ELFDATA2MSB)
	{
		ERROR_LOG(BOOT, "Invalid ELF header.");
		return false;
	}

	byteswapHeader(*header);

	const auto is_range_valid = [this](size_t offset, size_t size) {
		return offset <= m_size && size <= m_size - offset;
	};
	if (header->e_ehsize != sizeof(Elf32_Ehdr) ||
		(header->e_phnum != 0 && header->e_phentsize != sizeof(Elf32_Phdr)) ||
		(header->e_shnum != 0 && header->e_shentsize != sizeof(Elf32_Shdr)) ||
		!is_range_valid(header->e_phoff, sizeof(Elf32_Phdr) * header->e_phnum) ||
		!is_range_valid(header->e_shoff, sizeof(Elf32_Shdr) * header->e_shnum) ||
		(header->e_shstrndx != SHN_UNDEF && header->e_shstrndx >= header->e_shnum))
	{
		ERROR_LOG(BOOT, "Invalid ELF header table.");
		return false;
	}

	segments = (Elf32_Phdr*)(base + header->e_phoff);
	sections = (Elf32_Shdr*)(base + header->e_shoff);

	for (int i = 0; i < GetNumSegments(); i++)
	{
		byteswapSegment(segments[i]);
		if (!is_range_valid(segments[i].p_offset, segments[i].p_filesz) ||
			segments[i].p_filesz > segments[i].p_memsz)
		{
			ERROR_LOG(BOOT, "Invalid ELF program header %d.", i);
			return false;
		}
	}

	for (int i = 0; i < GetNumSections(); i++)
	{
		byteswapSection(sections[i]);
		if (sections[i].sh_type != SHT_NOBITS &&
			!is_range_valid(sections[i].sh_offset, sections[i].sh_size))
		{
			ERROR_LOG(BOOT, "Invalid ELF section header %d.", i);
			return false;
		}
	}
	entryPoint = header->e_entry;
	return true;
}

const char* ElfReader::GetSectionName(int section) const
{
	if (!m_is_valid || section < 0 || section >= header->e_shnum ||
		sections[section].sh_type == SHT_NULL)
	{
		return nullptr;
	}

	const Elf32_Shdr& string_section = sections[header->e_shstrndx];
	const size_t name_offset = sections[section].sh_name;
	const char* const ptr = (const char*)GetSectionDataPtr(header->e_shstrndx);

	if (!ptr || name_offset >= string_section.sh_size ||
		!std::memchr(ptr + name_offset, '\0', string_section.sh_size - name_offset))
	{
		return nullptr;
	}

	return ptr + name_offset;
}

// This is just a simple elf loader, good enough to load elfs generated by devkitPPC
bool ElfReader::LoadIntoMemory()
{
	if (!m_is_valid)
		return false;

	INFO_LOG(MASTER_LOG, "String section: %i", header->e_shstrndx);

	// Should we relocate?
	bRelocate = (header->e_type != ET_EXEC);

	if (bRelocate)
	{
		PanicAlert("Error: Dolphin doesn't know how to load a relocatable elf.");
		return false;
	}

	INFO_LOG(MASTER_LOG, "%i segments:", header->e_phnum);

	// Copy segments into ram.
	for (int i = 0; i < header->e_phnum; i++)
	{
		Elf32_Phdr* p = segments + i;

		INFO_LOG(MASTER_LOG, "Type: %i Vaddr: %08x Filesz: %i Memsz: %i ", p->p_type, p->p_vaddr,
			p->p_filesz, p->p_memsz);

		if (p->p_type == PT_LOAD)
		{
			u32 writeAddr = p->p_vaddr;
			const u8* src = GetSegmentPtr(i);
			u32 srcSize = p->p_filesz;
			u32 dstSize = p->p_memsz;

			Memory::CopyToEmu(writeAddr, src, srcSize);
			if (srcSize < dstSize)
				Memory::Memset(writeAddr + srcSize, 0, dstSize - srcSize);  // zero out bss

			INFO_LOG(MASTER_LOG, "Loadable Segment Copied to %08x, size %08x", writeAddr, p->p_memsz);
		}
	}

	INFO_LOG(MASTER_LOG, "Done loading.");
	return true;
}

SectionID ElfReader::GetSectionByName(const char* name, int firstSection) const
{
	for (int i = firstSection; i < header->e_shnum; i++)
	{
		const char* secname = GetSectionName(i);

		if (secname != nullptr && strcmp(name, secname) == 0)
			return i;
	}
	return -1;
}

bool ElfReader::LoadSymbols()
{
	if (!m_is_valid)
		return false;

	bool hasSymbols = false;
	SectionID sec = GetSectionByName(".symtab");
	if (sec != -1)
	{
		const u32 string_section_index = sections[sec].sh_link;
		if (string_section_index >= header->e_shnum)
		{
			ERROR_LOG(BOOT, "Invalid ELF symbol string table.");
			return false;
		}

		const Elf32_Shdr& string_section = sections[string_section_index];
		const char* stringBase = (const char*)GetSectionDataPtr(string_section_index);
		if (!stringBase)
		{
			ERROR_LOG(BOOT, "ELF symbol string table has no data.");
			return false;
		}

		// We have a symbol table!
		Elf32_Sym* symtab = (Elf32_Sym*)(GetSectionDataPtr(sec));
		if (!symtab)
		{
			ERROR_LOG(BOOT, "ELF symbol table has no data.");
			return false;
		}

		int numSymbols = sections[sec].sh_size / sizeof(Elf32_Sym);
		for (int sym = 0; sym < numSymbols; sym++)
		{
			int size = Common::swap32(symtab[sym].st_size);
			if (size == 0)
				continue;

			// int bind = symtab[sym].st_info >> 4;
			int type = symtab[sym].st_info & 0xF;
			int sectionIndex = Common::swap16(symtab[sym].st_shndx);
			int value = Common::swap32(symtab[sym].st_value);
			const size_t name_offset = Common::swap32(symtab[sym].st_name);
			if (name_offset >= string_section.sh_size ||
				!std::memchr(stringBase + name_offset, '\0', string_section.sh_size - name_offset))
			{
				ERROR_LOG(BOOT, "Invalid ELF symbol name %d.", sym);
				return false;
			}
			const char* name = stringBase + name_offset;
			if (bRelocate)
				value += sectionAddrs[sectionIndex];

			int symtype = Symbol::SYMBOL_DATA;
			switch (type)
			{
			case STT_OBJECT:
				symtype = Symbol::SYMBOL_DATA;
				break;
			case STT_FUNC:
				symtype = Symbol::SYMBOL_FUNCTION;
				break;
			default:
				continue;
			}
			g_symbolDB.AddKnownSymbol(value, size, name, symtype);
			hasSymbols = true;
		}
	}
	g_symbolDB.Index();
	return hasSymbols;
}
