[package]
name = "slippi_rust_extensions"
description = "An internal library that exposes entry points via the C FFI."
version = "0.1.0"
authors = []
repository = ""
edition = "2021"
publish = false

[build-dependencies]
cbindgen = "0.24.3"

[lib]
crate-type = ["cdylib"]

[features]
default = []
playback = []
