[package]
name = "slippi_rust_extensions"
description = "An internal library that exposes entry points via the C FFI."
version = "0.1.0"
authors = []
repository = ""
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true

[build-dependencies]
cbindgen = "0.24.3"

[features]
default = []
playback = []

[dependencies]
# This can be removed once Rust 1.70 is out.
once_cell = "1.17.1"

# We disable the "attributes" feature as we don't currently need it and it brings
# in extra dependencies.
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = "0.3"
